version: '3.9'
services:
  pytop:
    restart: always
    image: ubuntu/python
    container_name: 'python-container'
    working_dir: '/home/usr/mounted/'
    tty: true
    volumes:
      - ./:/home/usr/mounted
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    shm_size: 4gb
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
